language: node_js

notifications:
  email: false

node_js:
- 12

before_install:
- export PATH="$(yarn bin):${PATH}"

script:
- echo "Skipping tests"
# - npm test

after_script:
#- cp coverage/lcov.info coverage.lcov
#- node node_modules/.bin/codecov
- ./tools/continuous-deployment.travis.sh
