language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
- stable

before_install:
- yarn global add npm5 greenkeeper-lockfile@1

before_script:
- greenkeeper-lockfile-update

script:
- npm test
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
- ./tools/continuous-deployment.travis.sh
- node node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
- node node_modules/.bin/codecov

after_script:
- greenkeeper-lockfile-upload
