language: node_js

notifications:
  email: false

node_js:
  - 13

os:
  - linux

before_install:
  - export PATH="$(yarn bin):${PATH}"

script:
  - npm test

after_script:
  - cp coverage/lcov.info coverage.lcov
  - node node_modules/.bin/codecov
  - ./tools/continuous-deployment.travis.sh
